/**
 * @author Ygor Oliveira - Yasmim Candelária - Juan Gonçalves Dias - Filipe Vital da Silva
 * @since 17/05/2021
 */
package View;

import Controller.ClienteController;
import Controller.ItemVendaController;
import Controller.LancheController;
import Controller.VendaController;
import DAO.ItemVendaDAO;
import DAO.VendaDAO;
import Model.ClienteVip;
import Model.Venda;
import Model.VendaVip;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaVendas extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
        getContentPane().setBackground(new Color(255,228,181));
        setLocationRelativeTo(null);
        setResizable(false);
        tblCliente.getColumnModel().getColumn(0).setPreferredWidth(2);//id
        tblCliente.getColumnModel().getColumn(1).setPreferredWidth(100);//nome
        tblCliente.getColumnModel().getColumn(2).setPreferredWidth(35);//nascimento
        tblCliente.getColumnModel().getColumn(3).setPreferredWidth(60);//cpf
        tblCliente.getColumnModel().getColumn(4).setPreferredWidth(5);//sexo
        tblCliente.getColumnModel().getColumn(5).setPreferredWidth(35);//estado
        tblCliente.getColumnModel().getColumn(6).setPreferredWidth(5);//uf
        tblCliente.getColumnModel().getColumn(7).setPreferredWidth(120);//logradouro
        tblCliente.getColumnModel().getColumn(8).setPreferredWidth(5);//numero
        tblCliente.getColumnModel().getColumn(9).setPreferredWidth(40);//complemento
        tblCliente.getColumnModel().getColumn(10).setPreferredWidth(60);//telefone
        tblCliente.getColumnModel().getColumn(11).setPreferredWidth(60);//celular
        tblCliente.getColumnModel().getColumn(12).setPreferredWidth(120);//email
        
        tblLanche.getColumnModel().getColumn(0).setPreferredWidth(2);
        tblLanche.getColumnModel().getColumn(1).setPreferredWidth(50);
        tblLanche.getColumnModel().getColumn(2).setPreferredWidth(50);
        tblLanche.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblLanche.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblLanche.getColumnModel().getColumn(5).setPreferredWidth(10);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnNotaFiscal = new javax.swing.JButton();
        btnLixeira = new javax.swing.JButton();
        btnCarrinho = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        btnPesquisaNomeProd = new javax.swing.JButton();
        txtPesquisaProduto = new javax.swing.JTextField();
        btnPesquisaTipo = new javax.swing.JButton();
        txtPesquisaTipo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLanche = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnPesquisaCPF = new javax.swing.JButton();
        btnPesquisaNome = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPesquisaNome = new javax.swing.JTextField();
        txtPesquisaCPF = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cbbDesComum = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vendas");
        setBackground(new java.awt.Color(255, 228, 181));

        jPanel7.setBackground(new java.awt.Color(255, 228, 181));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..:: Lanches Disponíveis ::..", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel12.setBackground(new java.awt.Color(255, 228, 181));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..:: Operações ::..", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnNotaFiscal.setBackground(new java.awt.Color(255, 228, 181));
        btnNotaFiscal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/notaFiscal.png"))); // NOI18N
        btnNotaFiscal.setBorderPainted(false);
        btnNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotaFiscalActionPerformed(evt);
            }
        });

        btnLixeira.setBackground(new java.awt.Color(255, 228, 181));
        btnLixeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Lixeira.png"))); // NOI18N
        btnLixeira.setBorderPainted(false);
        btnLixeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLixeiraActionPerformed(evt);
            }
        });

        btnCarrinho.setBackground(new java.awt.Color(255, 228, 181));
        btnCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart-icon (1).png"))); // NOI18N
        btnCarrinho.setBorderPainted(false);
        btnCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrinhoActionPerformed(evt);
            }
        });

        btnAdicionar.setBackground(new java.awt.Color(255, 228, 181));
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Add-item-icon.png"))); // NOI18N
        btnAdicionar.setBorderPainted(false);
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnLixeira, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnNotaFiscal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLixeira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(btnNotaFiscal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnCarrinho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 228, 181));
        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..:: Pesquisa ::..", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Nome:");

        btnPesquisaNomeProd.setBackground(new java.awt.Color(255, 228, 181));
        btnPesquisaNomeProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Very-Basic-Search-icon.png"))); // NOI18N
        btnPesquisaNomeProd.setToolTipText("Pesquisar por nome");
        btnPesquisaNomeProd.setBorderPainted(false);
        btnPesquisaNomeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNomeProdActionPerformed(evt);
            }
        });

        btnPesquisaTipo.setBackground(new java.awt.Color(255, 228, 181));
        btnPesquisaTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Very-Basic-Search-icon.png"))); // NOI18N
        btnPesquisaTipo.setToolTipText("Pesquisar por tipo");
        btnPesquisaTipo.setBorderPainted(false);
        btnPesquisaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaTipoActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Tipo Produto:");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisaNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addComponent(btnPesquisaNomeProd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tblLanche.setBackground(new java.awt.Color(153, 204, 255));
        tblLanche.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sabor", "Tipo", "Preço unitário", "Qtd. em estoque", "Acompanhamento"
            }
        ));
        jScrollPane4.setViewportView(tblLanche);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 228, 181));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..:: Carrinho de Compras ::..", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        tblCarrinho.setBackground(new java.awt.Color(153, 204, 255));
        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sabor", "Tipo", "Preço unitário", "Acompanhamento"
            }
        ));
        jScrollPane3.setViewportView(tblCarrinho);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnVoltar.setBackground(new java.awt.Color(255, 228, 181));
        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SetinhaIcon.png"))); // NOI18N
        btnVoltar.setBorderPainted(false);
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 228, 181));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..:: Clientes cadastrados ::..", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        tblCliente.setBackground(new java.awt.Color(153, 204, 255));
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Nascimento", "CPF", "Sexo", "Estado", "UF", "Logradouro", "Nº", "Complemento", "Telefone", "Celular", "E-mail", "Vip?", "Nivel Vip"
            }
        ));
        jScrollPane2.setViewportView(tblCliente);

        jPanel2.setBackground(new java.awt.Color(255, 228, 181));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..:: Pesquisa ::..", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        btnPesquisaCPF.setBackground(new java.awt.Color(255, 228, 181));
        btnPesquisaCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Very-Basic-Search-icon.png"))); // NOI18N
        btnPesquisaCPF.setToolTipText("Pesquisar por CPF");
        btnPesquisaCPF.setBorderPainted(false);
        btnPesquisaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaCPFActionPerformed(evt);
            }
        });

        btnPesquisaNome.setBackground(new java.awt.Color(255, 228, 181));
        btnPesquisaNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Very-Basic-Search-icon.png"))); // NOI18N
        btnPesquisaNome.setToolTipText("Pesquisar por nome");
        btnPesquisaNome.setBorderPainted(false);
        btnPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaNomeActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("CPF:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Nome:");

        try {
            txtPesquisaCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPesquisaCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtPesquisaCPFMouseEntered(evt);
            }
        });
        txtPesquisaCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaCPFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addComponent(btnPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 228, 181));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Adicionar desconto (apenas clientes comuns):");

        cbbDesComum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.00", "0.05", "0.1", "0.15" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbbDesComum, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbbDesComum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel23.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Clientes vips já possuem desconto fixo de acordo com seu nível.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel23)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaTipoActionPerformed
        if(txtPesquisaTipo.getText().trim().equals("")){
            listarLanches();
        }else{
            listarTipoLanches();
        }

    }//GEN-LAST:event_btnPesquisaTipoActionPerformed

    private void btnPesquisaNomeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNomeProdActionPerformed
        if(txtPesquisaProduto.getText().trim().equals("")){
            listarLanches();
        }else{
            listarNomeLanches();
        }
    }//GEN-LAST:event_btnPesquisaNomeProdActionPerformed

    private void btnNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotaFiscalActionPerformed
        
        try {
        
        String desPedido ="Resumo da compra:" + "\n";
        String precoTotal="";
        double soma = 0;
            
        for (int i = 0; i<tblCarrinho.getModel().getRowCount();i++){

        int idLanche = Integer.parseInt(tblCarrinho.getValueAt(i,0).toString());
        String nome = tblCarrinho.getValueAt(i,1).toString();
        String modelo = tblCarrinho.getValueAt(i,2).toString();
        String tipo = tblCarrinho.getValueAt(i,3).toString();
        Double preco = Double.parseDouble(tblCarrinho.getValueAt(i,4).toString());
        
        soma +=preco;
        desPedido += "\nId Lanche: " + (int) idLanche + "\n" + 
                "Nome: " + nome + "\nPreço unitário: " + preco;
        
        }
        
        int clienteSelecionado = tblCliente.getSelectedRow();
        int idSelecionado = 0;
        
        //Variáveis cliente VIP:
        String vip = tblCliente.getValueAt(clienteSelecionado, 13).toString();
        int Nivelvip = Integer.parseInt(tblCliente.getValueAt(clienteSelecionado, 14).toString());
        String brindeVip = "";
        double precoTotalVip = 0;
        
        //Variáveis cliente Comum:
        double precoTotalComum = 0;
        
        if(vip.equals("Sim")){
            
            VendaVip obj01 = new VendaVip();            
            ClienteVip obj02 = new ClienteVip();
            double descontoFixo = obj02.getDescontoFixo(Nivelvip);
            
            precoTotalVip = obj01.calcularDesconto(soma, descontoFixo);
            
            JOptionPane.showMessageDialog(null,desPedido+"\nDesconto de cliente vip: "+descontoFixo
                            + "\nPreço total da compra: "+precoTotalVip);
        
        }else{
            brindeVip = "Venda comum";
            double descontoComum = Double.parseDouble(cbbDesComum.getSelectedItem().toString());
            Venda obj = new Venda();
            precoTotalComum = obj.calcularDesconto(soma, descontoComum);
            JOptionPane.showMessageDialog(null,desPedido+"\nDesconto de cliente comum: "+descontoComum
                            + "\nPreço total da compra: "+precoTotalComum);
        }
   }    
        catch (Exception e) {
            
             JOptionPane.showMessageDialog(this,"Insira itens no carrinho e selecione algum cliente!");
             return;
        }
    }//GEN-LAST:event_btnNotaFiscalActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        try {
            
        int linhaSelecionada = tblLanche.getSelectedRow();
        int idLanche = Integer.parseInt(tblLanche.getValueAt(linhaSelecionada,0).toString());
        String nome = tblLanche.getValueAt(linhaSelecionada,1).toString();
        String sabor = tblLanche.getValueAt(linhaSelecionada,2).toString();
        String tipo = tblLanche.getValueAt(linhaSelecionada,3).toString();
        Double preco = Double.parseDouble(tblLanche.getValueAt(linhaSelecionada,4).toString());
        int qtdEstoque = Integer.parseInt(tblLanche.getValueAt(linhaSelecionada,5).toString());
        String acompanhamento = tblLanche.getValueAt(linhaSelecionada,6).toString();

        
        if(qtdEstoque == 0){
          JOptionPane.showMessageDialog(this,"Este lanche não possui estoque para vendas!");
          return;
        
        }
        
        DefaultTableModel model = (DefaultTableModel) tblCarrinho.getModel();
        
        int idCarrinho =0, contaProd = 0;
        for (int i = 0; i<tblCarrinho.getModel().getRowCount();i++){
            
         idCarrinho = Integer.parseInt(tblCarrinho.getValueAt(i,0).toString());
         
         if(idCarrinho == idLanche){
             contaProd+=1;
             if(contaProd == qtdEstoque){
                    JOptionPane.showMessageDialog(this,"Estoque insuficiente para adicionar este lanche de novo! \nQuantidade no carrinho: "+contaProd+"\nQuantidade em estoque: "+qtdEstoque);
                    return;
             }
         }    

        }
        
        model.addRow(new Object []{idLanche, nome, sabor, tipo, preco, acompanhamento});

        }
        
        catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Selecione algum ítem para adicionar ao carrinho!");
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnLixeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLixeiraActionPerformed
        try {
            ((DefaultTableModel) tblCarrinho.getModel()).removeRow(tblCarrinho.getSelectedRow());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Selecione algum item para remover!");
            return;
        }
    }//GEN-LAST:event_btnLixeiraActionPerformed

    private void btnCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrinhoActionPerformed
        if(tblCarrinho.getModel().getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"Seu carrinho está vazio!");
            return;
        }
        
        if(tblCliente.getModel().getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"Pesquise um cliente abaixo ou cadastre no gerenciamento.");
            return;
        }
        
        int clienteSelecionado = tblCliente.getSelectedRow();
        int idSelecionado = 0;
        
        if(clienteSelecionado>=0){
            idSelecionado = Integer.parseInt(tblCliente.getValueAt(clienteSelecionado, 0).toString());
        }else{
            JOptionPane.showMessageDialog(this, "Selecione um cliente responsável!");
            return;
        }
        
        Date hoje = new Date();

        Calendar cal = Calendar.getInstance(); 
        cal.setTime(hoje); 
        cal.add(Calendar.DATE, 1);
        hoje = cal.getTime();
       
        int FkIdCliente = idSelecionado;
        Double precoTotal = 0.00;
        Double precoUnitario = 0.00;
        
        for (int i = 0; i<tblCarrinho.getModel().getRowCount();i++){

        int idLanche = Integer.parseInt(tblCarrinho.getValueAt(i,0).toString());
        String nome = tblCarrinho.getValueAt(i,1).toString();
        String modelo = tblCarrinho.getValueAt(i,2).toString();
        String tipo = tblCarrinho.getValueAt(i,3).toString();
        precoUnitario = Double.parseDouble(tblCarrinho.getValueAt(i,4).toString());
        
        precoTotal +=precoUnitario;

        }
        
        double descontoVenda = 0;
        
        //Variáveis cliente VIP:
        String vip = tblCliente.getValueAt(clienteSelecionado, 13).toString();
        int Nivelvip = Integer.parseInt(tblCliente.getValueAt(clienteSelecionado, 14).toString());
        String brindeVip = "";
        double precoTotalVip = 0;
        
        //Variáveis cliente Comum:
        double precoTotalComum = 0;
        
        if(vip.equals("Sim")){
            
            VendaVip obj01 = new VendaVip();
            brindeVip = obj01.escolhaBrinde();
            
            ClienteVip obj02 = new ClienteVip();
            double descontoFixo = obj02.getDescontoFixo(Nivelvip);
            
            precoTotalVip = obj01.calcularDesconto(precoTotal, descontoFixo);
            
            JOptionPane.showMessageDialog(null,"Desconto de cliente vip: "+descontoFixo
                            + "\nPreço total da compra: "+precoTotalVip);
            
            descontoVenda = precoTotalVip;
            
            
           
        }else{
            brindeVip = "Venda comum";
            double descontoComum = Double.parseDouble(cbbDesComum.getSelectedItem().toString());
            Venda obj = new Venda();
            precoTotalComum = obj.calcularDesconto(precoTotal, descontoComum);
            JOptionPane.showMessageDialog(null,"Desconto de cliente comum: "+descontoComum
                            + "\nPreço total da compra: "+precoTotalComum);
            descontoVenda = precoTotalComum;
          
        }
        
        
        if(VendaController.Salvar(hoje, precoTotal, descontoVenda, brindeVip, FkIdCliente) == true){
            
        int FkIdVenda = VendaDAO.idVenda;
         
        for (int i = 0; i<tblCarrinho.getModel().getRowCount();i++){
            
        int idLanche = Integer.parseInt(tblCarrinho.getValueAt(i,0).toString());
        
        int fkIdLanche = idLanche;
        
        if(ItemVendaController.Salvar(FkIdVenda,fkIdLanche) == true){

        }else{
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar ítens de venda!");
        }
        }
           JOptionPane.showMessageDialog(this,"Venda realizada com sucesso!");
           TelaInicial menu = new TelaInicial();
           menu.setVisible(true);
           dispose();
         
        }else{
            JOptionPane.showMessageDialog(this,"Erro ao realizar venda!");
        
        }
     
    }//GEN-LAST:event_btnCarrinhoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnPesquisaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaCPFActionPerformed
        if(txtPesquisaCPF.getText().equals("   .   .   -  ")){
            listarClientes();

        }

        else{

            try {
                String[] consulta = ClienteController.consultarPorCPF(txtPesquisaCPF.getText());

                DefaultTableModel modelo = new DefaultTableModel();
                modelo = (DefaultTableModel) tblCliente.getModel();

                modelo.setRowCount(0);
                modelo.addRow(consulta);
            } catch (Exception e) {

                JOptionPane.showMessageDialog(this,"CPF não encontrado!");
            }
        }
    }//GEN-LAST:event_btnPesquisaCPFActionPerformed

    private void btnPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaNomeActionPerformed
        if(txtPesquisaNome.getText().trim().equals("")){
            listarClientes();
        }else{
            listarPorNome();

        }
    }//GEN-LAST:event_btnPesquisaNomeActionPerformed

    private void txtPesquisaCPFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaCPFMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaCPFMouseEntered

    private void txtPesquisaCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaCPFActionPerformed
         public void listarLanches(){
        
        ArrayList<String []> listaLanches = LancheController.listar();
        
        //Passo os dados pra model
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tblLanche.getModel();
        
        //Zero o modelo antes de exibir para evitar duplicidades
        modelo.setRowCount(0);
        
        for (String[] listaLanche : listaLanches) {
            modelo.addRow(listaLanche);
        }
    
    }
     public void listarNomeLanches(){
        
        ArrayList<String []> listaLanches = LancheController.listarPorNome(txtPesquisaProduto.getText());
        
        //Passo os dados pra model
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tblLanche.getModel();
        
        //Zero o modelo antes de exibir para evitar duplicidades
        modelo.setRowCount(0);
        
        for (String[] listaLanche : listaLanches) {
            modelo.addRow(listaLanche);
        }
    
    }
     public void listarTipoLanches(){
        
        ArrayList<String []> listaLanches = LancheController.listarPorTipo(txtPesquisaTipo.getText());
        
        //Passo os dados pra model
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tblLanche.getModel();
        
        //Zero o modelo antes de exibir para evitar duplicidades
        modelo.setRowCount(0);
        
        for (String[] listaLanche : listaLanches) {
            modelo.addRow(listaLanche);
        }
    
    }
     public void listarClientes(){
        
        ArrayList<String []> listaClientes = ClienteController.listar();
        
        //Passo os dados pra model
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tblCliente.getModel();
        
        //Zero o modelo antes de exibir para evitar duplicidades
        modelo.setRowCount(0);
        
        for (String[] listaCliente : listaClientes) {
            modelo.addRow(listaCliente);
        }
    
    }
        
    
        public void listarPorNome(){
        
        ArrayList<String []> listaClientes = ClienteController.listarPorNome(txtPesquisaNome.getText());
        
        //Passo os dados pra model
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel) tblCliente.getModel();
        
        //Zero o modelo antes de exibir para evitar duplicidades
        modelo.setRowCount(0);
        
        for (String[] listaCliente : listaClientes) {
            modelo.addRow(listaCliente);
        }
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCarrinho;
    private javax.swing.JButton btnLixeira;
    private javax.swing.JButton btnNotaFiscal;
    private javax.swing.JButton btnPesquisaCPF;
    private javax.swing.JButton btnPesquisaNome;
    private javax.swing.JButton btnPesquisaNomeProd;
    private javax.swing.JButton btnPesquisaTipo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbbDesComum;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblCarrinho;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblLanche;
    private javax.swing.JFormattedTextField txtPesquisaCPF;
    private javax.swing.JTextField txtPesquisaNome;
    private javax.swing.JTextField txtPesquisaProduto;
    private javax.swing.JTextField txtPesquisaTipo;
    // End of variables declaration//GEN-END:variables
}
